from django.utils.translation import gettext_lazy as _
from datetime import datetime

COUNTRIES_CHOICES = [
    ('AF', _('Afghanistan')), ('AX', _('Åland Islands')), ('AL', _('Albania')),
    ('DZ', _('Algeria')), ('AS', _('American Samoa')), ('AD', _('Andorra')),
    ('AO', _('Angola')), ('AI', _('Anguilla')), ('AQ', _('Antarctica')),
    ('AG', _('Antigua and Barbuda')), ('AR', _('Argentina')), ('AM', _('Armenia')),
    ('AW', _('Aruba')), ('AU', _('Australia')), ('AT', _('Austria')),
    ('AZ', _('Azerbaijan')), ('BS', _('Bahamas')), ('BH', _('Bahrain')),
    ('BD', _('Bangladesh')), ('BB', _('Barbados')), ('BY', _('Belarus')),
    ('BE', _('Belgium')), ('BZ', _('Belize')), ('BJ', _('Benin')),
    ('BM', _('Bermuda')), ('BT', _('Bhutan')), ('BO', _('Bolivia')),
    ('BQ', _('Bonaire, Sint Eustatius and Saba')), ('BA', _('Bosnia and Herzegovina')),
    ('BW', _('Botswana')), ('BV', _('Bouvet Island')), ('BR', _('Brazil')),
    ('IO', _('British Indian Ocean Territory')), ('BN', _('Brunei Darussalam')),
    ('BG', _('Bulgaria')), ('BF', _('Burkina Faso')), ('BI', _('Burundi')),
    ('CV', _('Cabo Verde')), ('KH', _('Cambodia')), ('CM', _('Cameroon')),
    ('CA', _('Canada')), ('KY', _('Cayman Islands')),
    ('CF', _('Central African Republic')), ('TD', _('Chad')), ('CL', _('Chile')),
    ('CN', _('China')), ('CO', _('Colombia')), ('KM', _('Comoros')),
    ('CD', _('Congo')), ('CK', _('Cook Islands')), ('CR', _('Costa Rica')),
    ('HR', _('Croatia')), ('CU', _('Cuba')), ('CW', _('Curaçao')), ('CY', _('Cyprus')),
    ('CZ', _('Czechia')), ('DK', _('Denmark')), ('DJ', _('Djibouti')),
    ('DM', _('Dominica')), ('DO', _('Dominican Republic')), ('EC', _('Ecuador')),
    ('EG', _('Egypt')), ('SV', _('El Salvador')), ('GQ', _('Equatorial Guinea')),
    ('ER', _('Eritrea')), ('EE', _('Estonia')), ('SZ', _('Eswatini')),
    ('ET', _('Ethiopia')), ('FK', _('Falkland Islands  [Malvinas]')),
    ('FO', _('Faroe Islands')), ('FJ', _('Fiji')), ('FI', _('Finland')),
    ('FR', _('France')), ('GF', _('French Guiana')), ('PF', _('French Polynesia')),
    ('TF', _('French Southern Territories')), ('GA', _('Gabon')), ('GM', _('Gambia')),
    ('GE', _('Georgia')), ('DE', _('Germany')), ('GH', _('Ghana')),
    ('GI', _('Gibraltar')), ('GR', _('Greece')), ('GL', _('Greenland')),
    ('GD', _('Grenada')), ('GP', _('Guadeloupe')), ('GU', _('Guam')),
    ('GT', _('Guatemala')), ('GG', _('Guernsey')), ('GN', _('Guinea')),
    ('GW', _('Guinea-Bissau')), ('GY', _('Guyana')), ('HT', _('Haiti')),
    ('HM', _('Heard Island and McDonald Islands')), ('VA', _('Holy See')),
    ('HN', _('Honduras')), ('HK', _('Hong Kong')), ('HU', _('Hungary')),
    ('IS', _('Iceland')), ('IN', _('India')), ('ID', _('Indonesia')),
    ('IR', _('Iran')), ('IQ', _('Iraq')), ('IE', _('Ireland')),
    ('IM', _('Isle of Man')), ('IL', _('Israel')), ('IT', _('Italy')),
    ('CI', _('Ivory Coast')), ('JM', _('Jamaica')), ('JP', _('Japan')),
    ('JE', _('Jersey')), ('JO', _('Jordan')), ('KZ', _('Kazakhstan')),
    ('KE', _('Kenya')), ('KI', _('Kiribati')),
    ('KP', _('Korea (Democratic Republic of)')), ('KR', _('Korea (Republic of)')),
    ('KW', _('Kuwait')), ('KG', _('Kyrgyzstan')), ('LA', _('Lao Democratic Republic')),
    ('LV', _('Latvia')), ('LB', _('Lebanon')), ('LS', _('Lesotho')),
    ('LR', _('Liberia')), ('LY', _('Libya')), ('LI', _('Liechtenstein')),
    ('LT', _('Lithuania')), ('LU', _('Luxembourg')), ('MO', _('Macao')),
    ('MG', _('Madagascar')), ('MW', _('Malawi')), ('MY', _('Malaysia')),
    ('MV', _('Maldives')), ('ML', _('Mali')), ('MT', _('Malta')),
    ('MH', _('Marshall Islands')), ('MQ', _('Martinique')), ('MR', _('Mauritania')),
    ('MU', _('Mauritius')), ('YT', _('Mayotte')), ('MX', _('Mexico')),
    ('FM', _('Micronesia (Federated States of)')), ('MD', _('Moldova (the Republic of)')),
    ('MC', _('Monaco')), ('MN', _('Mongolia')), ('ME', _('Montenegro')),
    ('MS', _('Montserrat')), ('MA', _('Morocco')), ('MZ', _('Mozambique')),
    ('MM', _('Myanmar')), ('NA', _('Namibia')), ('NR', _('Nauru')),
    ('NP', _('Nepal')), ('NL', _('Netherlands')), ('NC', _('New Caledonia')),
    ('NZ', _('New Zealand')), ('NI', _('Nicaragua')), ('NE', _('Niger')),
    ('NG', _('Nigeria')), ('NU', _('Niue')), ('NF', _('Norfolk Island')),
    ('MK', _('North Macedonia')), ('MP', _('Northern Mariana Islands')),
    ('NO', _('Norway')), ('OM', _('Oman')), ('PK', _('Pakistan')),
    ('PW', _('Palau')), ('PS', _('Palestine, State of')), ('PA', _('Panama')),
    ('PG', _('Papua New Guinea')), ('PY', _('Paraguay')), ('PE', _('Peru')),
    ('PH', _('Philippines')), ('PN', _('Pitcairn')), ('PL', _('Poland')),
    ('PT', _('Portugal')), ('PR', _('Puerto Rico')), ('QA', _('Qatar')),
    ('RE', _('Réunion')), ('RO', _('Romania')), ('RU', _('Russian Federation')),
    ('RW', _('Rwanda')), ('BL', _('Saint Barthélemy')),
    ('SH', _('Saint Helena, Ascension and Tristan da Cunha')),
    ('KN', _('Saint Kitts and Nevis')), ('LC', _('Saint Lucia')),
    ('MF', _('Saint Martin (French part)')), ('PM', _('Saint Pierre and Miquelon')),
    ('VC', _('Saint Vincent and the Grenadines')), ('WS', _('Samoa')),
    ('SM', _('San Marino')), ('ST', _('Sao Tome and Principe')),
    ('SA', _('Saudi Arabia')), ('SN', _('Senegal')), ('RS', _('Serbia')),
    ('SC', _('Seychelles')), ('SL', _('Sierra Leone')), ('SG', _('Singapore')),
    ('SX', _('Sint Maarten (Dutch part)')), ('SK', _('Slovakia')), ('SI', _('Slovenia')),
    ('SB', _('Solomon Islands')), ('SO', _('Somalia')), ('ZA', _('South Africa')),
    ('GS', _('South Georgia and the South Sandwich Islands')), ('SS', _('South Sudan')),
    ('ES', _('Spain')), ('LK', _('Sri Lanka')), ('SD', _('Sudan')), ('SR', _('Suriname')),
    ('SJ', _('Svalbard and Jan Mayen')), ('SE', _('Sweden')), ('CH', _('Switzerland')),
    ('SY', _('Syrian Arab Republic')), ('TW', _('Taiwan (Province of China)')),
    ('TJ', _('Tajikistan')), ('TZ', _('Tanzania, the United Republic of')),
    ('TH', _('Thailand')), ('TL', _('Timor-Leste')), ('TG', _('Togo')),
    ('TK', _('Tokelau')), ('TO', _('Tonga')), ('TT', _('Trinidad and Tobago')),
    ('TN', _('Tunisia')), ('TR', _('Turkey')), ('TM', _('Turkmenistan')),
    ('TC', _('Turks and Caicos Islands')), ('TV', _('Tuvalu')), ('UG', _('Uganda')),
    ('UA', _('Ukraine')), ('AE', _('United Arab Emirates')),
    ('GB', _('United Kingdom of Great Britain and Northern Ireland')),
    ('UK', _('United Kingdom of Great Britain and Northern Ireland')),
    ('US', _('United States of America')), ('UY', _('Uruguay')), ('UZ', _('Uzbekistan')),
    ('VU', _('Vanuatu')), ('VE', _('Venezuela (Bolivarian Republic of)')),
    ('VN', _('Viet Nam')), ('VG', _('Virgin Islands (British)')),
    ('VI', _('Virgin Islands (U.S.)')), ('WF', _('Wallis and Futuna')),
    ('EH', _('Western Sahara')), ('YE', _('Yemen')),
    ('ZM', _('Zambia')), ('ZW', _('Zimbabwe')),
]

GENRES = [
    {"name": "Action"},
    {"name": "Adventure"},
    {"name": "Animation"},
    {"name": "Biography"},
    {"name": "Comedy"},
    {"name": "Crime"},
    {"name": "Documentary"},
    {"name": "Drama"},
    {"name": "Family"},
    {"name": "Fantasy"},
    {"name": "Film-Noir"},
    {"name": "History"},
    {"name": "Horror"},
    {"name": "Music"},
    {"name": "Musical"},
]

DIRECTORS = [
    {'name': 'Quentin Tarantino', 'date_birth': datetime(1963, 1, 1), 'country_of_birth': 'US',
     'bio': 'Quentin Tarantino is an American director, writer, and producer.'},
    {'name': 'James Cameron', 'date_birth': datetime(1954, 1, 1), 'country_of_birth': 'UK',
     'bio': 'James Cameron is an English film director, producer, and writer.'},
    {'name': 'Steven Spielberg', 'date_birth': datetime(1946, 1, 1), 'country_of_birth': 'US',
     'bio': 'Steven Spielberg is an American film director, producer, and writer.'},
    {'name': 'Martin Scorsese', 'date_birth': datetime(1942, 1, 1), 'country_of_birth': 'US',
     'bio': 'Martin Scorsese is an American film director, producer, and writer.'},
    {'name': 'Alfred Hitchcock', 'date_birth': datetime(1899, 1, 1), 'country_of_birth': 'US',
     'bio': 'Alfred Hitchcock is an English film director, producer, and writer.'},
    {'name': 'Ridley Scott', 'date_birth': datetime(1925, 1, 1), 'country_of_birth': 'UK',
     'bio': 'Ridley Scott is an English film director, producer, and writer.'},
    {'name': 'John Ford', 'date_birth': datetime(1925, 1, 1), 'country_of_birth': 'UK',
     'bio': 'John Ford is an English film director, producer, and writer.'},
    {'name': 'Michael Bay', 'date_birth': datetime(1961, 1, 1), 'country_of_birth': 'UK',
     'bio': 'Michael Bay is an American film director, producer, and writer.'},
    {'name': 'Tim Burton', 'date_birth': datetime(1958, 1, 1), 'country_of_birth': 'US',
     'bio': 'Tim Burton is an American film director, producer, and writer.'},
    {'name': 'George Lucas', 'date_birth': datetime(1944, 1, 1), 'country_of_birth': 'US',
     'bio': 'George Lucas is an American film director, producer, and writer.'},
    {'name': 'Clint Eastwood', 'date_birth': datetime(1930, 1, 1), 'country_of_birth': 'US',
     'bio': 'Clint Eastwood is an American film director, producer, and writer.'},
    {'name': 'John Carpenter', 'date_birth': datetime(1931, 1, 1), 'country_of_birth': 'US',
     'bio': 'John Carpenter is an American film director, producer, and writer.'},
    {'name': 'Alfred Hitchcock II', 'date_birth': datetime(1935, 1, 1), 'country_of_birth': 'US',
     'bio': 'Alfred Hitchcock II is an American film director, producer, and writer.'},
    {'name': 'Stanley Kubrick', 'date_birth': datetime(1927, 1, 1), 'country_of_birth': 'US',
     'bio': 'Stanley Kubrick is an American film director, producer, and writer.'},
    {'name': 'John G. Avildsen', 'date_birth': datetime(1931, 1, 1), 'country_of_birth': 'US',
        'bio': 'John G. Avildsen is an American film director, producer, and writer.'},
    {'name': 'Peter Jackson', 'date_birth': datetime(1961, 1, 1), 'country_of_birth': 'UK',
        'bio': 'Peter Jackson is an English film director, producer, and writer.'},
    {'name': 'Christopher Nolan', 'date_birth': datetime(1970, 1, 1), 'country_of_birth': 'UK',
        'bio': 'Christopher Nolan is an English film director, producer, and writer.'},
]

ACTORS = [
    {'name': 'Tom Hanks', 'date_birth': datetime(1956, 1, 1), 'country_of_birth': 'US',
     'bio': 'Tom Hanks is an American actor and producer.'},
    {'name': 'Robert De Niro', 'date_birth': datetime(1943, 1, 1), 'country_of_birth': 'US',
     'bio': 'Robert De Niro is an American actor and producer.'},
    {'name': 'Al Pacino', 'date_birth': datetime(1940, 1, 1), 'country_of_birth': 'US',
     'bio': 'Al Pacino is an American actor and producer.'},
    {'name': 'Dustin Hoffman', 'date_birth': datetime(1953, 1, 1), 'country_of_birth': 'US',
     'bio': 'Dustin Hoffman is an American actor and producer.'},
    {'name': 'Jack Nicholson', 'date_birth': datetime(1937, 1, 1), 'country_of_birth': 'US',
     'bio': 'Jack Nicholson is an American actor and producer.'},
    {'name': 'Tom Cruise', 'date_birth': datetime(1962, 1, 1), 'country_of_birth': 'US',
     'bio': 'Tom Cruise is an American actor and producer.'},
    {'name': 'John Travolta', 'date_birth': datetime(1954, 1, 1), 'country_of_birth': 'US',
     'bio': 'John Travolta is an American actor and producer.'},
    {'name': 'Harrison Ford', 'date_birth': datetime(1942, 1, 1), 'country_of_birth': 'US',
     'bio': 'Harrison Ford is an American actor and producer.'},
    {'name': 'Sean Connery', 'date_birth': datetime(1930, 1, 1), 'country_of_birth': 'UK',
     'bio': 'Sean Connery is an American actor and producer.'},
    {'name': 'Daniel Day-Lewis', 'date_birth': datetime(1956, 1, 1), 'country_of_birth': 'UK',
     'bio': 'Daniel Day-Lewis is an American actor and producer.'},
    {'name': 'Morgan Freeman', 'date_birth': datetime(1937, 1, 1), 'country_of_birth': 'US',
     'bio': 'Morgan Freeman is an American actor and producer.'},
    {'name': 'Brad Pitt', 'date_birth': datetime(1963, 1, 1), 'country_of_birth': 'US',
     'bio': 'Brad Pitt is an American actor and producer.'},
    {'name': 'Jackie Chan', 'date_birth': datetime(1962, 1, 1), 'country_of_birth': 'US',
     'bio': 'Jackie Chan is an American actor and producer.'},
    {'name': 'Sylvester Stallone', 'date_birth': datetime(1946, 1, 1), 'country_of_birth': 'US',
     'bio': 'Sylvester Stallone is an American actor and producer.'},
    {'name': 'John Wayne', 'date_birth': datetime(1946, 1, 1), 'country_of_birth': 'US',
     'bio': 'John Wayne is an American actor and producer.'},
    {'name': 'Harrison Ford', 'date_birth': datetime(1942, 1, 1), 'country_of_birth': 'US',
     'bio': 'Harrison Ford is an American actor and producer.'},
    {'name': 'Sean Connery', 'date_birth': datetime(1930, 1, 1), 'country_of_birth': 'UK',
     'bio': 'Sean Connery is an American actor and producer.'},
    {'name': 'Daniel Day-Lewis', 'date_birth': datetime(1956, 1, 1), 'country_of_birth': 'UK',
     'bio': 'Daniel Day-Lewis is an American actor and producer.'},
    {'name': 'Morgan Freeman', 'date_birth': datetime(1937, 1, 1), 'country_of_birth': 'US',
     'bio': 'Morgan Freeman is an American actor and producer.'},
]

MOVIES = [
    {"title": "Inception", "release_year": 2010,
     "description": "A thief who steals corporate secrets through use of the dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
     "average_rating": 8.8, "duration": 120, "director": "Christopher Nolan", "language": "English",
     "trailer_link": "https://www.youtube.com/watch?v=1jwc3-_7yv8", "genre": "Sci-Fi", "country_of_origin": "US"},
    {"title": "The Lord of the Rings: The Two Towers", "release_year": 2002,
     "description": "A young Hobbit named Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to save his own existence.",
     "average_rating": 8.7, "duration": 180, "director": "Peter Jackson", "language": "English",
     "trailer_link": "https://www.youtube.com/watch?v=V75dMMIW2B4", "genre": "Fantasy", "country_of_origin": "US"},
    {"title": "Forrest Gump", "release_year": 1994, "description": "Forrest Gump", "average_rating": 8.8,
     "duration": 142, "director": "Robert Zemeckis", "language": "English",
     "trailer_link": "https://www.youtube.com/watch?v=uPIEn0M8su0", "genre": "Drama", "country_of_origin": "US"},
    {"title": "The Matrix", "release_year": 1999,
     "description": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
     "average_rating": 8.7, "duration": 136, "director": "Lana Wachowski", "language": "English",
     "trailer_link": "https://www.youtube.com/watch?v=vKQi3bB8XoQ", "genre": "Sci-Fi", "country_of_origin": "US"},
    {"title": "The Lord of the Rings: The Fellowship of the Ring", "release_year": 2001,
     "description": "A memorable battle between the forces of good and evil, the ancient evil of Gondor, the result of a dark power rising from the South, and the strength of the One Ring, which has been lost for centuries.",
     "average_rating": 8.9, "duration": 178, "director": "Peter Jackson", "language": "English",
     "trailer_link": "https://www.youtube.com/watch?v=V75dMMIW2B4", "genre": "Fantasy", "country_of_origin": "US"},
    {"title": "The Lord of the Rings: The Return of the King", "release_year": 2003,
     "description": "Gandalf and Aragorn lead the World of Warcraft against Sauron, the Dark Lord, who is trying to take over the world.",
     "average_rating": 8.9, "duration": 201, "director": "Peter Jackson", "language": "English",
     "trailer_link": "https://www.youtube.com/watch?v=V75dMMIW2B4", "genre": "Fantasy", "country_of_origin": "US"},
    {"title": "The Dark Knight", "release_year": 2008,
     "description": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.",
     "average_rating": 9.0, "duration": 152, "director": "Christopher Nolan", "language": "English",
     "trailer_link": "https://www.youtube.com/watch?v=EXeTw3WrcwY", "genre": "Action", "country_of_origin": "US"},
    {"title": "The Dark Knight Rises", "release_year": 2012,
     "description": "Eight years after the Joker emerges from his mysterious past, he must return to Gotham City to clean up the city once and for all.",
     "average_rating": 9.0, "duration": 165, "director": "Christopher Nolan", "language": "English",
     "trailer_link": "https://www.youtube.com/watch?v=EXeTw3WrcwY", "genre": "Action", "country_of_origin": "US"},
    {"title": "The Hobbit: An Unexpected Journey", "release_year": 2012,
     "description": "A reluctant hobbit, Bilbo Baggins, sets out on a journey with a spirited group of dwarves, who are intent on reclaiming the Lonely Mountain for the kingdom of Erebor, which is in danger of being destroyed by an evil army of Orcs.",
     "average_rating": 8.9, "duration": 201, "director": "Peter Jackson", "language": "English",
     "trailer_link": "https://www.youtube.com/watch?v=V75dMMIW2B4", "genre": "Fantasy", "country_of_origin": "US"},
    {"title": "The Hobbit: The Desolation of Smaug", "release_year": 2013,
     "description": "The dwarves, along with Bilbo Baggins and Gandalf the Grey, continue their quest to reclaim Erebor, their homeland, from Smaug, the dragon of the sky.",
     "average_rating": 8.9, "duration": 178, "director": "Peter Jackson", "language": "English",
     "trailer_link": "https://www.youtube.com/watch?v=V75dMMIW2B4", "genre": "Fantasy", "country_of_origin": "US"},
    {"title": "The Hobbit: The Battle of the Five Armies", "release_year": 2014,
     "description": "Mere buddies, Frodo and Sam, encounter a creature they know as Gollum, a creature that seems to be more than a simple-minded hobbit. They must fight, and the evil wizard must be defeated.",
     "average_rating": 8.9, "duration": 201, "director": "Peter Jackson", "language": "English",
     "trailer_link": "https://www.youtube.com/watch?v=V75dMMIW2B4", "genre": "Fantasy", "country_of_origin": "US"},
    {"title": "The Hobbit: The Children of the Ring", "release_year": 2012,
     "description": "The dwarves, along with Bilbo Baggins and Gandalf the Grey, continue their quest to reclaim Erebor, their homeland, from Smaug, the dragon of the sky.",
     "average_rating": 8.9, "duration": 178, "director": "Peter Jackson", "language": "English",
     "trailer_link": "https://www.youtube.com/watch?v=V75dMMIW2B4", "genre": "Fantasy", "country_of_origin": "US"},
    {"title": "A Clockwork Orange", "release_year": 1971,
     "description": "A story of a young officer who is accused of a crime that he didn't commit.",
     "average_rating": 8.8, "duration": 138, "director": "Stanley Kubrick", "language": "English",
     "trailer_link": "https://www.youtube.com/watch?v=V75dMMIW2B4", "genre": "Drama", "country_of_origin": "US"},
    {"title": "A Clockwork Orange II", "release_year": 1972,
     "description": "A story of a young officer who is accused of a crime that he didn't commit.",
     "average_rating": 8.8, "duration": 138, "director": "Stanley Kubrick", "language": "English",
     "trailer_link": "https://www.youtube.com/watch?v=V75dMMIW2B4", "genre": "Drama", "country_of_origin": "US", "actors": ["Jack Nicholson", "Sylvester Stallone", "Harrison Ford"]},
]
